### ISSUE TITLE
work query returns serde error

### ISSUE THREAD

**Issue by magnusmanske** [mattsse/crossref-rs#3]
I am trying
`https://docs.rs/crossref/0.1.0/crossref/struct.Crossref.html#method.work`
with DOI "10.1371/journal.ppat.1007512" (code from master branch)

Searching on the CrossRef site gets the correct work, but from the work method I get:
```
Err(Error { ctx:
invalid serde: invalid length 0, expected struct Relation with 3 elements })
```

**Comment by mattsse** [comment]
Hi Magnus,

thanks for this issue. This has been fixed with fb1693912889e02cf545edf8bb18a15d7015d3c0
I tracked the problem down to the `Relations ` type which i defined as `HashMap<String, Relation>` which should be according to crossref api-spec [*A hashmap containing relation name, Relation pairs.*](https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#relations).

However the response of your DOI contains:

```
"relation": {
      "cites": []
    },
```
where the `Relation` value is now an empty array. weird. 
I changed the value type of the `Relations` hashmap to `serde_json::Value` for now...

I also updated the crate on [crates.io](https://crates.io/crates/crossref)
